

spring:
  cloud:
    gateway:
      routes:
        - id: account-service
          uri: http://localhost:9081
          predicates:
            - Path=/old-account/**
          filters:
            - RewritePath=/old-account/(?<segment>.*), /$\{segment}
#            - name: Hystrix
#              args:
#                name: fetchIngredients
#                fallbackUri: forward:/hystrixfallback
        - id: account-rest-service
          uri: http://localhost:8082
          predicates:
            - Path=/account/**
          filters:
            - RewritePath=/account/(?<segment>.*), /$\{segment}
#            - name: Hystrix
#              args:
#                name: fetchIngredients
#                fallbackUri: forward:/hystrixfallback
        - id: employee-service
          uri: http://localhost:8083
          predicates:
            - Path=/employee/**
          filters:
            - RewritePath=/employee/(?<segment>.*), /$\{segment}

logging:
  level:
    org.springframework.cloud.gateway: trace
    org.springframework.security: debug

management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8081